@startuml
left to right direction
skinparam packageStyle rectangle

actor "Gracz" as G
actor "Organizator wydarzeń" as O
actor "Administrator systemu" as A
actor "Czujnik / Czytnik QR" as S <<Hardware>>

package "Obsługa interakcji sprzętowych" {
    usecase "Odczyt identyfikatora obiektu" as UC1
    usecase "Przypisanie przedmiotu do ekwipunku" as UC2
    usecase "Odblokowanie materiału multimedialnego" as UC3
    usecase "Aktualizacja odkrytego obszaru mapy" as UC4
    usecase "Zgłoszenie awarii technicznej" as UC6

    usecase "Powiązanie akcji systemowej z czujnikiem" as UC7
    usecase "Weryfikacja opóźnień transmisji danych" as UC8
    usecase "Ustawienie parametrów powiadomień fabularnych" as UC9

    UC1 ..> UC2 : <<invokes>>
    UC1 ..> UC3 : <<invokes>>
    UC1 ..> UC4 : <<invokes>>
}

G --> UC1
G --> UC6

S --> UC1

O --> UC7
O --> UC9

A --> UC8
@enduml
