@startuml zarzadzanie_cyklem_zycia_wydarzenia

left to right direction

skinparam packageStyle rectangle

actor "Gracz" as gracz
actor "Organizator wydarzeń" as org
actor "Administrator systemu" as admin

package "Zarządzanie Cyklem Życia Wydarzenia" {
usecase "Utworzenie wydarzenia" as UC1
usecase "Obsługa procesu akceptacji gry" as UC2
usecase "Wyszukiwanie wydarzeń" as UC3
usecase "Zapisanie się na wydarzenie" as UC4
usecase "Zapisanie na listę rezerwową" as UC4_ext
usecase "Wystawienie oceny wydarzeniu" as UC5

UC4 <.. UC4_ext : <<extend>>
}


org --> UC1
admin --> UC2
gracz --> UC3
gracz --> UC4
gracz --> UC5

@enduml